---

kind: pipeline
name: default
steps:
- name: test
  image: golang:1.13-alpine
  commands:
  - go build
  - go test -v

- name: notify
  image: plugins/slack
  settings:
    channel: server_messages
    secrets: [ slack_webhook_url ]
    when:
      status: [ success, failure ]