---
kind: pipeline
name: default
steps:
  - name: test
    image: golang:1.13-alpine
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go mod download
      - go build
      - go test -v

  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      port:
        from_secret: ssh_port
      key:
        from_secret: ssh_key
      passphrase:
        from_secret: ssh_passphrase
      script:
        - sh deploy.sh

  - name: notify
    image: plugins/slack
    settings:
      channel: server_messages
      username: drone
      webhook:
        from_secret: slack_webhook_url
      when:
        status: [success, failure]
      template: >
        {{#success build.status}}
          Repo name: {{repo.name}}
          Commit author: {{build.author}}
          Commit: {{build.commit}} [{{build.branch}}]
          Message: go build {{build.number}} succeeded.
          Duration: {{since build.created}}
        {{else}}
          Repo name: {{repo.name}}
          Commit author: {{build.author}}
          Commit: {{build.commit}} [{{build.branch}}]
          go build {{build.number}} failed.
        {{/success}}
